services:
  django:
    build: .
    container_name: haystack_django
    command: /bin/bash
    links:
      - postgres:postgres
    ports:
      - 8000:8000
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - ./:/usr/app
    working_dir: /usr/app
  postgres:
    image: postgres:17.6-bookworm
    container_name: haystack_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - ./db-data:/var/lib/postgresql/data
