services:
  python:
    build: .
    container_name: haystack_python
    command: /bin/bash
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - ./:/usr/app
    working_dir: /usr/app
