# Generated by Django 5.2.6 on 2025-10-02 18:15

import django.db.models.deletion
import haystack.core.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0002_job_description_job_easy_apply_job_flexibility_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', haystack.core.fields.AutoCreatedField(auto_now_add=True)),
                ('updated_at', haystack.core.fields.AutoUpdatedField(auto_now=True)),
                ('uuid', haystack.core.fields.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('keywords', models.CharField(max_length=255)),
                ('easy_apply', models.BooleanField(default=False)),
                ('flexibility', models.CharField(choices=[('hybrid', 'Hybrid'), ('onsite', 'Onsite'), ('remote', 'Remote')], default='onsite', max_length=6)),
                ('last_executed', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='searches', to='jobs.location')),
            ],
            options={
                'verbose_name': 'search',
                'verbose_name_plural': 'searches',
            },
        ),
    ]
