# Generated by Django 5.2.6 on 2025-10-02 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_event'),
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='search',
            unique_together={('keywords', 'location', 'easy_apply', 'flexibility')},
        ),
    ]
