# Generated by Django 5.2.7 on 2025-10-10 02:14

import django.db.models.deletion
import haystack.core.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', haystack.core.fields.AutoCreatedField(auto_now_add=True)),
                ('updated_at', haystack.core.fields.AutoUpdatedField(auto_now=True)),
                ('uuid', haystack.core.fields.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('parser', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SearchSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', haystack.core.fields.AutoCreatedField(auto_now_add=True)),
                ('updated_at', haystack.core.fields.AutoUpdatedField(auto_now=True)),
                ('uuid', haystack.core.fields.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('last_executed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('scheduled', 'Scheduled'), ('running', 'Running'), ('success', 'Success'), ('error', 'Error')], default='idle', max_length=9)),
                ('is_active', models.BooleanField(default=True)),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.search')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.source')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='search',
            name='sources',
            field=models.ManyToManyField(related_name='searches', through='search.SearchSource', to='search.source'),
        ),
    ]
