# Generated by Django 5.2.7 on 2025-10-10 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_source_searchsource_search_sources'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='searchsource',
            unique_together={('search', 'source')},
        ),
    ]
