# Generated by Django 5.2.7 on 2025-10-08 19:29

import django.db.models.deletion
import haystack.core.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', haystack.core.fields.AutoCreatedField(auto_now_add=True)),
                ('updated_at', haystack.core.fields.AutoUpdatedField(auto_now=True)),
                ('uuid', haystack.core.fields.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(unique=True)),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', haystack.core.fields.AutoCreatedField(auto_now_add=True)),
                ('updated_at', haystack.core.fields.AutoUpdatedField(auto_now=True)),
                ('uuid', haystack.core.fields.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('geo_id', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', haystack.core.fields.AutoCreatedField(auto_now_add=True)),
                ('updated_at', haystack.core.fields.AutoUpdatedField(auto_now=True)),
                ('uuid', haystack.core.fields.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(unique=True)),
                ('date_posted', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.company')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='jobs.location')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
