# Generated by Django 5.2.6 on 2025-10-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='job',
            name='easy_apply',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='flexibility',
            field=models.CharField(choices=[('hybrid', 'Hybrid'), ('onsite', 'Onsite'), ('remote', 'Remote')], default='onsite', max_length=6),
        ),
        migrations.AddField(
            model_name='job',
            name='raw_html',
            field=models.TextField(default=''),
        ),
    ]
