# Generated by Django 5.2.7 on 2025-10-08 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_date_found_job_easy_apply_job_flexibility_and_more'),
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='search',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='search.search'),
        ),
    ]
