# Generated by Django 5.2.7 on 2025-10-08 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='job',
            name='raw_html',
            field=models.TextField(default=''),
        ),
    ]
