# Generated by Django 5.2.7 on 2025-10-08 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_description_job_raw_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='date_applied',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('dismissed', 'Dismissed'), ('saved', 'Saved'), ('applied', 'Applied'), ('rejected', 'Rejected'), ('interviewing', 'Interviewing'), ('offer', 'Offer'), ('accepted', 'Accepted'), ('withdrawn', 'Withdrawn')], default='new', max_length=12),
        ),
        migrations.AlterField(
            model_name='job',
            name='date_posted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
