# Generated by Django 5.2.7 on 2025-10-08 23:15

import django.db.models.deletion
import haystack.core.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_date_applied_job_status_alter_job_date_posted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', haystack.core.fields.AutoCreatedField(auto_now_add=True)),
                ('updated_at', haystack.core.fields.AutoUpdatedField(auto_now=True)),
                ('uuid', haystack.core.fields.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('event_type', models.CharField(choices=[('note', 'Note'), ('status', 'Status')], max_length=6)),
                ('note', models.TextField(default='')),
                ('old_status', models.CharField(choices=[('new', 'New'), ('dismissed', 'Dismissed'), ('saved', 'Saved'), ('applied', 'Applied'), ('rejected', 'Rejected'), ('interviewing', 'Interviewing'), ('offer', 'Offer'), ('accepted', 'Accepted'), ('withdrawn', 'Withdrawn')], default='', max_length=12)),
                ('new_status', models.CharField(choices=[('new', 'New'), ('dismissed', 'Dismissed'), ('saved', 'Saved'), ('applied', 'Applied'), ('rejected', 'Rejected'), ('interviewing', 'Interviewing'), ('offer', 'Offer'), ('accepted', 'Accepted'), ('withdrawn', 'Withdrawn')], default='', max_length=12)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='jobs.job')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
