# Generated by Django 5.2.7 on 2025-10-10 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_event'),
        ('search', '0002_source_searchsource_search_sources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='search',
        ),
        migrations.AddField(
            model_name='job',
            name='search_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='search.searchsource'),
        ),
    ]
