# Generated by Django 5.2.7 on 2025-10-14 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_remove_job_search_job_search_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='new_status',
            field=models.CharField(choices=[('new', 'New'), ('expired', 'Expired'), ('dismissed', 'Dismissed'), ('saved', 'Saved'), ('applied', 'Applied'), ('rejected', 'Rejected'), ('interviewing', 'Interviewing'), ('offer', 'Offer'), ('accepted', 'Accepted'), ('withdrawn', 'Withdrawn')], default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='event',
            name='old_status',
            field=models.CharField(choices=[('new', 'New'), ('expired', 'Expired'), ('dismissed', 'Dismissed'), ('saved', 'Saved'), ('applied', 'Applied'), ('rejected', 'Rejected'), ('interviewing', 'Interviewing'), ('offer', 'Offer'), ('accepted', 'Accepted'), ('withdrawn', 'Withdrawn')], default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('expired', 'Expired'), ('dismissed', 'Dismissed'), ('saved', 'Saved'), ('applied', 'Applied'), ('rejected', 'Rejected'), ('interviewing', 'Interviewing'), ('offer', 'Offer'), ('accepted', 'Accepted'), ('withdrawn', 'Withdrawn')], default='new', max_length=12),
        ),
    ]
