# Generated by Django 5.2.7 on 2025-10-14 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_event_new_status_alter_event_old_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='flexibility',
            field=models.CharField(blank=True, choices=[('hybrid', 'Hybrid'), ('onsite', 'Onsite'), ('remote', 'Remote')], default=None, max_length=6, null=True),
        ),
    ]
